apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-app-deployment
  labels:
    app: voting-app-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-app-pod
      app: voting-app-demo
  template:
    metadata:
      name: postgres-app-pod
      labels:
        name: postgres-app-pod
        app: voting-app-demo
    spec:
      containers:
      - name: postgres
        image: postgres:9.4
        env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
