apiVersion: v1
kind: Service
metadata:
  name: redis-app-service
  labels:
    name: redis-app-service
    app: voting-app-demo
spec:
  ports:
  - targetPort: 6379
    port:  6379
  selector:
    name: redis-app-pod
    app: voting-app-demo