apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    name: voting-app-service
    app: voting-app-demo
spec:
  type: LoadBalancer
  ports:
  - targetPort: 80
    port:  80
  selector:
    name: redis-app-pod
    app: voting-app-demo