apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    app: voting-app-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      name: result-app-pod
      app: voting-app-demo
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        app: voting-app-demo
    spec:
      containers:
      - name: examplevotingapp-result
        image: dockersamples/examplevotingapp_result
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
