apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: result-app-pod
    app: voting-app-demo
spec:
  containers:
  - name: examplevotingapp-result
    image: dockersamples/examplevotingapp_result
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
